site_name: Rekonstrukce bytu
repo_url: https://github.com/surquest/flat-renovation
docs_dir: src
nav:
  - Úvod: index.md
  - Kuchyně: kitchen.md
theme:
  name: material
  features:
    - content.code.annotate
plugins:
    - drawio_file
    - search
    - mkdocs-pdf
    # - macros
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - "extras/glossary.md"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

