site_name: Rekonstrukce bytu
repo_url: https://github.com/surquest/flat-renovation
docs_dir: src
nav:
  - Úvod: index.md
  - Pokoje:
    - Kuchyně: rooms/kitchen.md
    - Obývací pokoj: rooms/living-room.md
    - Koupelna malá: rooms/bathroom-small.md
    - Koupelna velká: rooms/bathroom-big.md
    - Ložnice západ: rooms/bedroom-west.md
    - Ložnice jih: rooms/bedroom-south.md
  - Stavební práce: construction.md

theme:
  name: material
  features:
    - content.tooltips
plugins:
    - glightbox
    - drawio_file
    - search
    - mkdocs-pdf
    # - macros
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - extras/equipment.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

